"""Prove the Hilbert settings match `cqed_scf`'s own restricted implementation.

The unrestricted reference numbers in this directory are only trustworthy if
Hilbert is being driven with the same Hamiltonian and the same coupling
convention that `cqed_scf` uses.  There is no `uscf.py` yet to check against, so
we check the *restricted* analogue, where `cqed_scf` already has a production
implementation:

    Hilbert  qed-scf (POLARITONIC_RHF)  ==  cqed_scf CQED-RHF
    Hilbert  qed-dft (POLARITONIC_RKS)  ==  cqed_scf CQED-RKS/PBE0

If this script passes, the same option set applied to `reference = uhf` / `uks`
is generating apples-to-apples QED-UHF / QED-UKS references.

Usage
-----
    python validate_protocol_restricted.py
"""

from __future__ import annotations

import sys

import numpy as np

sys.path.insert(0, "/Users/jfoley19/Code")

import psi4  # noqa: E402
import hilbert  # noqa: E402,F401  (registers the qed-* procedures)

from cqed_scf import CQEDCalculator, CQEDConfig  # noqa: E402

from systems import lambda_to_hilbert_coupling  # noqa: E402

# Water, closed shell -- the system `cqed_scf`'s existing canonical examples use.
GEOMETRY = """
0 1
O 0.000000000000 0.000000000000 -0.068516219320
H 0.000000000000 -0.790689573744 0.543701060715
H 0.000000000000  0.790689573744 0.543701060715
no_reorient
no_com
symmetry c1
"""

LAMBDA_VECTOR = np.array([0.0, 0.0, 0.05])
OMEGA = 0.1
BASIS = "cc-pVDZ"
FUNCTIONAL = "PBE0"
TOL = 1.0e-10

SHARED_OPTIONS = {
    "basis": BASIS,
    "scf_type": "pk",
    "e_convergence": 1.0e-11,
    "d_convergence": 1.0e-10,
    "dft_spherical_points": 590,
    "dft_radial_points": 99,
}


def hilbert_energy(reference, driver_name, functional=None):
    psi4.core.clean()
    psi4.core.clean_options()
    psi4.core.clean_variables()

    mol = psi4.geometry(GEOMETRY)
    options = dict(SHARED_OPTIONS)
    options.update({
        "reference": reference,
        "hilbert__cavity_frequency": OMEGA,
        "hilbert__cavity_coupling_strength": lambda_to_hilbert_coupling(
            LAMBDA_VECTOR, OMEGA
        ),
        "hilbert__n_photon_states": 1,
        "hilbert__use_coherent_state_basis": True,
        "hilbert__maxiter": 500,
    })
    if functional is not None:
        options["hilbert__qed_dft_functional"] = functional
    psi4.set_options(options)
    return float(psi4.energy(driver_name, molecule=mol))


def cqed_scf_energy(reference, functional=None):
    psi4.core.clean()
    psi4.core.clean_options()
    psi4.core.clean_variables()

    config = CQEDConfig(
        lambda_vector=LAMBDA_VECTOR,
        omega=OMEGA,
        psi4_options=dict(SHARED_OPTIONS),
        reference=reference,
        functional=functional,
        density_fitting=False,
        charge=0,
        multiplicity=1,
        dispersion_policy="none",
        debug=False,
        quiet=True,
    )
    return float(CQEDCalculator(config=config).energy(GEOMETRY))


def main():
    psi4.core.be_quiet()
    psi4.set_memory("8 GB")

    cases = [
        ("CQED-RHF", "rhf", "qed-scf", None),
        (f"CQED-RKS/{FUNCTIONAL}", "rks", "qed-dft", FUNCTIONAL),
    ]

    lam_str = "(" + ", ".join(f"{v:.2f}" for v in LAMBDA_VECTOR) + ")"
    print(f"water / {BASIS} / lambda = {lam_str} / omega = {OMEGA}")
    print("=" * 84)
    print(f"{'method':<20s}{'hilbert / Eh':>22s}{'cqed_scf / Eh':>22s}{'difference':>16s}")
    print("-" * 84)

    failures = 0
    for label, reference, driver_name, functional in cases:
        e_hilbert = hilbert_energy(reference, driver_name, functional)
        e_cqed = cqed_scf_energy(reference, functional)
        delta = e_hilbert - e_cqed
        if abs(delta) > TOL:
            failures += 1
        print(f"{label:<20s}{e_hilbert:>22.12f}{e_cqed:>22.12f}{delta:>16.2e}")

    print("=" * 84)
    if failures:
        print(f"FAIL: {failures} case(s) differ by more than {TOL:.0e} Eh")
        sys.exit(1)
    print(f"PASS: both restricted methods agree to better than {TOL:.0e} Eh.")
    print("The same Hilbert option set is therefore valid for the QED-UHF / QED-UKS")
    print("references generated by run_hilbert_qed_uhf_uks.py.")


if __name__ == "__main__":
    main()
